"""
StS: A class called PowerNetwork is defined which describes the connections of a power grid where nodes can be
active participants or distributing power stations and edges are abstracted connections between those.
Edges can have weights which represent power fees.
JuH: the script powernetwork.py uses the library networkx to create random network with nodes and edges.
"""

import json
import random
import networkx as nx
from networkx.readwrite import json_graph
import matplotlib.pyplot as plt


class PowerNetwork:
    def __init__(self, name, network):
        """
        JuH: Parameters
        ----------
        name: string
        network: graph
        """
        self.name = name
        self.network = network
        # TODO currently first leaf node is interpreted as root node which might change
        self.leaf_nodes = sorted(n for n, d in self.network.degree() if d == 1)[1:]
        self.short_paths = {}

    def update_shortest_paths(self):
        """
        JuH: identifies the shortest paths in the grid and collects them in a dictionary.
        The dictionary is a mapping from the start node to the end node
        and contains all nodes in between along the shortest path.
        """
        self.short_paths = dict(nx.all_pairs_shortest_path(self.network))

    def to_image(self, width, height):
        """StS: saves image generated by plot function... somewhere?
        """
        fig = self.plot(False)
        fig.savefig(self.name + ".png")

    def plot(self, show=True):
        """plot: draws power network. Parameter show: displays image."""
        fig = plt.figure()
        # TODO: improved plot with or without Graphvis
        # from simply.plotting import plot_hierarchical
        # plot_hierarchical(self.network)
        nx.draw(self.network, with_labels=True, font_weight="bold", node_size=50)
        if show:
            plt.show()

        return fig

    def to_dict(self):
        """
        StS: returns dictionary of power network,
        which contains all necessary information about nodes and edges to rebuild the network.
        """
        return json_graph.node_link_data(self.network)

    def to_json(self):
        """StS: saves power network.
        Scenario.to_dict and Scenario.save use PowerNetwork.to_dict, instead.
        """
        filename = self.name + ".json"
        net_json = json_graph.node_link_data(self.network)
        json.dump(net_json, open(filename, "w"), indent=2)

    def add_actors_random(self, actors):
        """
        StS: This function inserts actors randomly into the network as leaf nodes
        (nodes with only one connection -> no child nodes).
        Parameters
        ----------
        actors: list
        Returns
        -------
        map: the map_actors for the scenario
        """
        base_id = max(self.network.nodes()) + 100
        num_actors = len(actors)
        actor_nodes = list([*range(base_id, base_id + len(actors), 1)])
        random.shuffle(actor_nodes)
        connections = random.choices(self.leaf_nodes, k=num_actors)
        map = {}
        while actor_nodes:
            a = actor_nodes.pop()
            c = connections.pop()
            map[a] = c
            self.network.add_edge(c, a)

        return map

    def add_actors_map(self, map):
        base_id = max(self.network.nodes()) + 100
        for a, c in map.items():
            self.network.add_edge(c, a + base_id)

        return map


def create_random(nodes):
    """
    StS: The function builds up a new power network with a given number of nodes.
    All edges between those nodes are given random weights between 0 and 1
    (only one decimal point saved -> resolution of 0.1).
    Parameters
    ----------
    nodes: integer

    Returns
    -------
    Object: new PowerNetwork
    """
    # TODO get number of leaves as parameter
    nw = nx.random_tree(nodes)

    # Add random weights in [0, 1] with 0.1 resolution
    for e in nw.edges:
        nw[e[0]][e[1]]["weight"] = random.randint(0, 10) * 0.1

    return PowerNetwork("random", nw)


def create_random2(nodes):
    """
    StS: I would say this function does not work,
    as in line 144 it tries to create edges between a leaf node and a node that does not exist. Unused function.
    Parameters
    ----------
    nodes: integer

    Returns
    -------
    object: new PowerNetwork
    """
    # TODO get number of leaves as parameter
    nw = nx.random_tree(nodes)

    # TODO might be useful to add actors as additional nodes after creation
    leaf_nodes = sorted(n for n, d in nw.degree() if d == 1)[1:]
    offset = 0
    for n in leaf_nodes:
        for i in range(random.randint(2, 5)):
            offset += 1
            nw.add_edge(n, nodes + offset)

    # Add random weights in [0, 1] with 0.1 resolution
    for e in nw.edges:
        nw[e[0]][e[1]]["weight"] = random.randint(0, 10) * 0.1

    return PowerNetwork("random", nw)


def load_network()
"""StS: create a random PowerNetwork. Unused."""
    nw = nx.random_lobster(3, 0.5, 0.2)
    return PowerNetwork("random", nw)
