"""
 JuH: The script scenario.py represents different scenarios and defines the proporties of a random scenario.
Directories are created for the Parameters of the class where the data from the scripts "actor.py" and "power_network.py" are safed and merged together.
Under consideration of the number of nodes and actors scenarios are created
"""

import json
from networkx.readwrite import json_graph
import pandas as pd
import random

from simply import actor
from simply import power_network


class Scenario:
    def __init__(self, network, actors, map_actors, rng_seed=None):
        """
        JuH: Parameters
        ----------
        network: specific power grid
        actors: examples of different prosumer
        map_actors: define where actors are located
        rng_seed: creates random number

        """
        self.rng_seed = rng_seed if rng_seed is not None else random.getrandbits(32)
        random.seed(self.rng_seed)

        self.power_network = network
        self.actors = list(actors)
        # maps node ids to actors
        self.map_actors = map_actors

    def from_config(path):
        pass

    def __str__(self):
        """
        JuH: create empty strings for the parameters of the class
        With __str__ strings are created out of class parameters. The column names of each of the dataframes are then converted to keys of the dictonaries.
        Returns
        -------
        object
        """
        return "Scenario(network: {}, actors: {}, map_actors: {})".format(
            self.power_network, self.actors, self.map_actors
        )

    def to_dict(self):
        return {
            "rng_seed": self.rng_seed,
            "power_network": {self.power_network.name: self.power_network.to_dict()},
            "actors": {a.id: a.to_dict() for a in self.actors},
            "map_actors": self.map_actors,
        }

    def save(self, dirpath):
        # create target directory
        dirpath.mkdir(parents=True, exist_ok=True)

        # save meta information
        dirpath.joinpath('_meta.inf').write_text(json.dumps({"rng_seed": self.rng_seed}))

        # save power network
        dirpath.joinpath('network.cfg').write_text(json.dumps({
            self.power_network.name: self.power_network.to_dict()
        }))

        # save actors
        for actor in self.actors:
            dirpath.joinpath(f'actor_{actor.id}.cfg').write_text(json.dumps(actor.to_dict()))

        # save map_actors
        dirpath.joinpath('map_actors.cfg').write_text(json.dumps(self.map_actors))


def from_dict(scenario_dict):
    """
    JuH: last item of the dictonary is removed after used and checks if the quantity of the dictionary is 0. Variables are created with "network", "pn" and "actors".
    Returns graph of the node-link data: Includes the skript powernetwork name and network of each run. Includes the script actor as a list with different parameters.

    Parameters
    ----------
    scenario_dict

    Returns
    -------
    object: dict
        Scenario with parameters out of the scripts "actor" and "power_network"
    """
    pn_name, pn_dict = scenario_dict["power_network"].popitem()
    assert len(scenario_dict["power_network"]) == 0, "Multiple power networks in scenario"
    network = json_graph.node_link_graph(pn_dict,
        directed = pn_dict.get("directed", False),
        multigraph = pn_dict.get("multigraph", False))
    pn = power_network.PowerNetwork(pn_name, network)

    actors = [
        actor.Actor(actor_id, pd.read_json(ai["df"]), ai["ls"], ai["ps"], ai["pm"])
        for actor_id, ai in scenario_dict["actors"].items()]

    return Scenario(pn, actors, scenario_dict["map_actors"], scenario_dict["rng_seed"])


def load(dirpath):
    """
    JuH: Create scenario from files that were generated by Scenario.save(). Creates empty list for actors and then loads actors into the list simultaneously.
    Parameters
    ----------
    dirpath: string

    Returns
    -------
    object: Scenario with parameters defined above
    """

    # read meta info
    meta_text = dirpath.joinpath('_meta.inf').read_text()
    meta = json.loads(meta_text)
    rng_seed = meta.get("rng_seed", None)

    # read power network
    network_text = dirpath.joinpath('network.cfg').read_text()
    network_json = json.loads(network_text)
    network_name = list(network_json.keys())[0]
    network_json = list(network_json.values())[0]
    network = json_graph.node_link_graph(network_json,
        directed = network_json.get("directed", False),
        multigraph = network_json.get("multigraph", False))
    pn = power_network.PowerNetwork(network_name, network)

    # read actors
    actor_files = dirpath.glob("actor_*.cfg")
    actors = []
    for f in sorted(actor_files):
        at = f.read_text()
        aj = json.loads(at)
        ai = [aj["id"], pd.read_json(aj["df"]), aj["ls"], aj["ps"], aj["pm"]]
        actors.append(actor.Actor(*ai))

    # read map_actors
    map_actor_text = dirpath.joinpath('map_actors.cfg').read_text()
    map_actors = json.loads(map_actor_text)

    return Scenario(pn, actors, map_actors, rng_seed)


def create_random(num_nodes, num_actors):
    """
    JuH: creates random scenario from given number of nodes and actors
    Parameters
    ----------
    num_nodes: integer
    num_actors: integer

    Returns
    -------
    object: Returns scenario object
    """
    pn = power_network.create_random(num_nodes)
    actors = [actor.create_random(i) for i in range(num_actors)]

    # Add actor nodes at random position in the network
    # One network node can contain several actors (using random.choices method)
    map_actors = pn.add_actors_random(actors)

    return Scenario(pn, actors, map_actors)


def create_random2(num_nodes, num_actors):
    # num_actors has to be much smaller than num_nodes
    pn = power_network.create_random(num_nodes)
    actors = [actor.create_random(i) for i in range(num_actors)]

    # Give actors a random position in the network
    actor_nodes = random.sample(pn.leaf_nodes, num_actors)
    map_actors = {actor.id: node_id for actor, node_id in zip(actors, actor_nodes)}

    # TODO tbd if actors are already part of topology ore create additional nodes
    # pn.add_actors_map(map_actors)

    return Scenario(pn, actors, map_actors)
